# Generated by Django 5.2.4 on 2025-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('in_process', 'In Process'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted'), ('saved', 'Saved')], default='', max_length=20)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
